// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  // Headers de segurança adicionais
  global: {
    // Impede vazamento de Referer
    'X-Client-Info': 'finlingo',
  }
});

// =====================================================
// SEGURANÇA: Não expor variáveis em console
// =====================================================
if (import.meta.env.DEV) {
  console.log('%c⚠️ Segurança: Nunca compartilhe suas variáveis de ambiente!', 'color: red; font-size: 14px;');
  console.log('%cAs chaves do Supabase são visíveis apenas para o app.', 'color: orange;');
}
